### PR TITLE
Add spacing to regionprops 

### PR DESCRIPTION
**Pull request by tibuch**
Hi @grlee77, 

As suggested in https://github.com/scikit-image/scikit-image/issues/5112 the changes to regionprops to respect spacings.

## Description
Add support for arbitrary pixel spacings to regionprops and moments.

## Checklist
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [x] Unit tests
    * Feret diameters are only tested for isotropic pixel spacings.
    * Perimeter functions only support isotropic pixel spacings.
    * Hu moments only support `spacing = (1, 1)`.
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

### CODE REVIEW

**Comment by grlee77** [comment]
Thanks @tibuch! It will be better to make the PR against scikit-image/main instead. Can you try changing the target of the PR to that? We can write in the PR comments that it is built on top of the moments-central-analytical branch, and 3390465 is the new component to be reviewed.

**Comment by grlee77** [comment]
Hey @tibuch, let me know if the suggestion here wasn't clear. I am happy to hop on a quick video chat at some point to pair up and help if that would be useful.

**Comment by tibuch** [comment]
Hi @grlee77, just didn't come around to do it yet. Should I only change the target and not rebase it onto scikit-image/main?

**Comment by grlee77** [comment]
> Hi @grlee77, just didn't come around to do it yet. Should I only change the target and not rebase it onto scikit-image/main?

Ideally, rebasing on main might be best for ease of review of just your commit. I wasn't sure your level of comfort/familiarity with git rebasing. You could try changing the target first and see if it looks clean or whether there are a lot of unrelated commits showing up.

**Comment by grlee77** [comment]
the prior comment wasn't to rush you, I just wanted to check in to make sure you weren't stuck

**Comment by tibuch** [comment]
Submitted the PR to scikit-image: https://github.com/scikit-image/scikit-image/pull/6296

**Pull request closed without merging**
